package com.fran.hibernateanotaciones2.entidades;

// Generated 13 dic 2022 18:56:56 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

/**
 * Libros generated by hbm2java
 */
@Entity
@Table(name = "libros")
public class Libros implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String titulo;
	private Set<Autores> autoreses = new HashSet<Autores>(0);

	public Libros() {
	}

	public Libros(int id) {
		this.id = id;
	}

	public Libros(int id, String titulo, Set<Autores> autoreses) {
		this.id = id;
		this.titulo = titulo;
		this.autoreses = autoreses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "titulo", length = 60)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "escribir", joinColumns = {
			@JoinColumn(name = "codlibro", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codautor", nullable = false, updatable = false) })
	public Set<Autores> getAutoreses() {
		return this.autoreses;
	}

	public void setAutoreses(Set<Autores> autoreses) {
		this.autoreses = autoreses;
	}

	@Override
	public String toString() {
		String resultado = "";
		resultado += "Id: " + id + "\n";
		resultado += "Título: " + titulo + "\n";
		if(autoreses.size()>0) {
			for(Autores autor : autoreses) {
				resultado += autor.getNombre() + "\n";
			}
		} else {
			resultado += "Este libro no tiene autor";
		}
		return resultado;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Libros other = (Libros) obj;
		return id == other.id;
	}
	
	

}
