package com.fran.hibernate2.entidades;

// Generated 18 nov 2022 15:52:35 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autores generated by hbm2java
 */
public class Autores implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String cod;
	private String nombre;
	private Set<Libros> libroses = new HashSet<Libros>(0);

	public Autores() {
	
	}

	public Autores(String cod) {
		this.cod = cod;
	}
	
	public Autores(String cod, String nombre) {
		this.cod = cod;
		this.nombre = nombre;
	}

	public Autores(String cod, String nombre, Set<Libros> libroses) {
		this.cod = cod;
		this.nombre = nombre;
		this.libroses = libroses;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Libros> getLibroses() {
		return this.libroses;
	}

	public void setLibroses(Set<Libros> libroses) {
		this.libroses = libroses;
	}

	@Override
	public String toString() {
		String resultado = "";
		resultado = "Código: " + cod +
				"\nNombre: " + nombre + "\n";
		for(Libros libro : libroses) {
			resultado += libro.getTitulo() + "\n";
		}		
		return resultado;
	}
	
	
	

}
