package com.fran.biblioteca1.entidades;

// Generated 15 nov 2022 18:22:22 by Hibernate Tools 6.1.3.Final

/**
 * Libros generated by hbm2java
 */
public class Libros implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String titulo;
	private String autor;

	public Libros() {
	}

	public Libros(int id) {
		this.id = id;
	}

	public Libros(int id, String titulo, String autor) {
		this.id = id;
		this.titulo = titulo;
		this.autor = autor;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@Override
	public String toString() {
		return "Libros [id=" + id + ", titulo=" + titulo + ", autor=" + autor + "]";
	}
	

}
